block-explosion:
  # Should we log and tracing for explosion?
  enable: true
  # Disable the explosion if no source can be tracking.
  disable-unknown: true
  # The message will broadcast to players that around 15 blocks nearby
  alert: "&cAn explosion near you has been blocked because that caused by unknown object."
entity-explosion:
  enable: true
  disable-unknown: true
  alert: "&cAn explosion near you has been blocked because that caused by unknown object."
fire:
  enable: true
  disable-unknown: true
  alert: "&cAn fire spreading/burning has been blocked because that caused by unknown object."
itemframe:
  enable: true
  disable-unknown: true
  alert: "&cBlocked item-frame destroy because that caused by unknown object."
painting:
  enable: true
  disable-unknown: true
    alert: "&cBlocked painting destroy because that caused by unknown object."