block-explosion:
  # Should we log and tracing for explosion?
  enable: true
  # Disable the explosion if no source can be tracking.
  disable-unknown: true
  # The message will broadcast to players that around 15 blocks nearby
  alert: "&cAn explosion near you has been blocked because that caused by unknown object."
entity-explosion:
  enable: true
  disable-unknown: true
  alert: "&cAn explosion near you has been blocked because that caused by unknown object."
fire:
  enable: true
  disable-unknown: true
  alert: "&cAn fire spreading/burning has been blocked because that caused by unknown object."

#tnt:
#  log: true
#  disable-when-target-not-found: true
#creeper:
#  log: true
#  disable-when-target-not-found: true
#endercrystal:
#  log: true
#  disable-when-target-not-found: true
#fireball:
#  log: true
#  disable-when-target-not-found: true
#tntminecart:
#  log: true
#  disable-when-target-not-found: true
#bed:
#  log: true
#  disable-when-target-not-found: true
#respawn-anchor:
#  log: true
#  disable-when-target-not-found: true
#other-explosive-blocks:
#  disable-when-target-not-found: true
#fire:
#  log: true
#  disable-burn-when-target-not-found: false
#  disable-spread-when-target-not-found: false


msgs:
  block-explode-blocked: "&cAn explosion near you has been blocked because caused by unknown object."

#msgs:
#  tnt-wont-break-blocks: "&cThis TNT explosion won't break any blocks because it was not triggered by a player."
#  creeper-wont-break-blocks: "&cThis Creeper explosion won't break any blocks because it was not triggered by a player."
#  endercrystal-wont-break-blocks: "&cThis End Crystal explosion won't break any blocks because it was not triggered by a player."
#  fireball-wont-break-blocks: "&cThis Fireball explosion won't break any blocks because it was not triggered by a player."
#  tntminecart-wont-break-blocks: "&cThis TNT Minecart explosion won't break any blocks because it was not triggered by a player."
#  bed-wont-break-blocks: "&cThis Bed explosion won't break any blocks because it was not triggered by a player."
#  respawn-anchor-wont-break-blocks: "&cThis Respawn Anchor explosion won't break any blocks because it was not triggered by a player."
#  other-explosive-block-wont-break-blocks: "&cThis explosive block explosion won't break any blocks because it was not triggered by a player."
#  fire-wont-burn-blocks: "&cFire won't burn any blocks because it was not ignited by a player."
#  fire-wont-spread: "&cFire won't spread because it was not ignited by a player."
