tnt:
  log: true
  disable-when-target-not-found: true
creeper:
  log: true
  disable-when-target-not-found: true
endercrystal:
  log: true
  disable-when-target-not-found: true
fireball:
  log: true
  disable-when-target-not-found: true
tntminecart:
  log: true
  disable-when-target-not-found: true
bed:
  log: true
msgs:
  tnt-wont-break-blocks: "&cThis TNT explosion won't break any blocks because it was not triggered by a player."
  creeper-wont-break-blocks: "&cThis Creeper explosion won't break any blocks because it was not triggered by a player."
  endercrystal-wont-break-blocks: "&cThis End Crystal explosion won't break any blocks because it was not triggered by a player."
  fireball-wont-break-blocks: "&cThis Fireball explosion won't break any blocks because it was not triggered by a player."
  tntminecart-wont-break-blocks: "&cThis TNT Minecart explosion won't break any blocks because it was not triggered by a player."